## Basic tensor tutorial

In [1]:
import torch 
import numpy as np

In [2]:
#Check GPU support
if torch.cuda.is_available():
    device = torch.device("cuda")

`torch.empty` makes empty tensors of the defined size. `size` can be set a single value (scalar), 2D, 3D, n-dimensionals tensors

In [3]:
x = torch.empty(1) #Scalar randomly initialized 
x3 = torch.empty(3) #3D vector randomly initialized 
print(x,x3)

tensor([1.8888e+31]) tensor([0., 0., 0.])


In [4]:
x4 = torch.empty(2,2,2,3) #
print(x4)

tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]],


        [[[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 7.3468e-40, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]]])


`numpy` like instantiation works in torch: 
```python
- torch.zeros
- torch.ones
- torch.rand
```
Finally we can provide the `dtype` for the tensor as well -- `float64`, `int`, `double`

In [5]:
x = torch.ones(2,2, dtype=torch.int)
print(x, x.size())

tensor([[1, 1],
        [1, 1]], dtype=torch.int32) torch.Size([2, 2])


In [6]:
#Creating tensor from list: 
list_rand = np.random.rand(10,1)
x = torch.tensor(list_rand)
print(x)

tensor([[6.4116e-01],
        [8.5331e-01],
        [6.6069e-01],
        [7.0937e-04],
        [4.1202e-01],
        [3.2125e-01],
        [6.1966e-02],
        [9.2504e-01],
        [4.7671e-01],
        [6.1907e-01]], dtype=torch.float64)


### Tensor operations

* z = x + y 
* z = torch.add(x, y)
* z = y.add_(x)

Operations -- `mul` `add` `sub` `div`

In [7]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.4425, 0.7765],
        [0.5643, 0.4267]])
tensor([[0.0109, 0.3211],
        [0.2134, 0.1709]])


In [8]:
z = x + y
#OR and better method
z = torch.add(x,y)
print(z)

tensor([[0.4534, 1.0976],
        [0.7777, 0.5976]])


In [9]:
#In-place addition -- any variable with _ trailing it will to in-place operation 
y.add_(x)
print(y)

tensor([[0.4534, 1.0976],
        [0.7777, 0.5976]])


In [10]:
z_mult = torch.mul(x,y) #element-wise multiplication
print(z_mult)

tensor([[0.2006, 0.8522],
        [0.4389, 0.2550]])


In [11]:
#Slicing operations 
x = torch.rand(5,3)
print(x)
print(x[:,0]) #0th column -- all rows 
print(x[1,1])

tensor([[0.0286, 0.9108, 0.2512],
        [0.7375, 0.6428, 0.0700],
        [0.2741, 0.7752, 0.1103],
        [0.7669, 0.8678, 0.7977],
        [0.8949, 0.7576, 0.4876]])
tensor([0.0286, 0.7375, 0.2741, 0.7669, 0.8949])
tensor(0.6428)


In [12]:
#Reshaping a tensor 
x = torch.rand(4,4)
print(x)
y = x.view(-1,8) #Like numpy, -1 is the place hold for the dimension which takes reminder of elements 
print(y)

tensor([[0.7477, 0.9545, 0.8371, 0.9566],
        [0.0519, 0.1198, 0.2492, 0.5988],
        [0.5605, 0.4806, 0.5125, 0.9870],
        [0.7686, 0.6541, 0.7816, 0.9467]])
tensor([[0.7477, 0.9545, 0.8371, 0.9566, 0.0519, 0.1198, 0.2492, 0.5988],
        [0.5605, 0.4806, 0.5125, 0.9870, 0.7686, 0.6541, 0.7816, 0.9467]])


## Converting torch tensors to numpy 

Here be careful that numpy tensors can only be handeled on the CPU and not on the GPU thus we will have to move the GPU tensors back to CPU. Also, the tensor being converted to numpy or vice-versa share the same memory location (if on CPU) so they will be linked. 

```python
if torch.cude.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device = device) #Directly on GPU 
    y = torch.ones(5) #Made on CPU 
    y = y.to(device) #Sent to GPU 
    
    z = x + y 
    z.to("cpu") 
```

In [13]:
# Torch to numpy array 
a = torch.rand(10)
print(a) 
b = a.numpy() 
print(type(b))

tensor([0.6440, 0.9498, 0.7319, 0.9332, 0.8487, 0.3334, 0.7086, 0.7679, 0.8033,
        0.8007])
<class 'numpy.ndarray'>


> NOTE: However both `a` and `b` share the same memory and thus point to same memory location -- so any edit to `a` would be made to `b` as well. 

In [14]:
a.add_(1.0)
print(a)
print(b)

tensor([1.6440, 1.9498, 1.7319, 1.9332, 1.8487, 1.3334, 1.7086, 1.7679, 1.8033,
        1.8007])
[1.6439948 1.9498271 1.7319177 1.933162  1.8486525 1.3334291 1.7085993
 1.7678998 1.8033237 1.8007493]


In [15]:
#From numpy to tensor 
b1 = torch.from_numpy(b)
print(b1)

tensor([1.6440, 1.9498, 1.7319, 1.9332, 1.8487, 1.3334, 1.7086, 1.7679, 1.8033,
        1.8007])


### To have a variable that is supposed to be optimized 

In [17]:
x = torch.ones(5, requires_grad = True)

In [18]:
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
